// Auto-Generated by FAKE; do not edit
namespace System
open System.Reflection

[<assembly: AssemblyTitleAttribute("YC.BioGraph")>]
[<assembly: AssemblyProductAttribute("YC.BioGraph")>]
[<assembly: AssemblyDescriptionAttribute("Bio graph parsing web demo")>]
[<assembly: AssemblyVersionAttribute("0.0")>]
[<assembly: AssemblyFileVersionAttribute("0.0")>]
do ()

module internal AssemblyVersionInformation =
    let [<Literal>] AssemblyTitle = "YC.BioGraph"
    let [<Literal>] AssemblyProduct = "YC.BioGraph"
    let [<Literal>] AssemblyDescription = "Bio graph parsing web demo"
    let [<Literal>] AssemblyVersion = "0.0"
    let [<Literal>] AssemblyFileVersion = "0.0"
